version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ./backend/dotnet_ddd/Dockerfile
    image: ddd.api
    container_name: ddd.api
    ports:
      - "5200:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ASPNETCORE_URLS=http://+"
    restart: on-failure
    depends_on:
      - db
  client:
    build:
      context: frontend/angular_ddd
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./angular:/project
      - /project/node_modules
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: ddd.db
    environment:
      SA_PASSWORD: "P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - 1434:1433 # exposed just for debugging purposes
